version: '3.8'
services:
  api:
    build: ./backend/api
    ports:
      - '3000:3000'
    volumes:
      - ./backend/api:/usr/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./backend/api/db/mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  notifications:
    build: ./backend/notifications
    ports:
      - '4000:4000'
