version: '3'
services:
  api:
    build: ./backend/api
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
      - storage.minio

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  storage.minio:
    container_name: storage.minio
    build:
      context: ./backend/storage
      dockerfile: Dockerfile
    volumes:
      - ./backend/storage/uploads:/storage/uploads
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password

  redis:
    image: redis:latest

  rabbitmq:
    image: rabbitmq:latest

  notifications:
    build: ./backend/notifications
    ports:
      - '4000:4000'
    depends_on:
      - redis
