version: '3.8'
services:
  api:
    build: ./backend/api
    ports:
      - '3000:3000'
    volumes:
      - ./backend/api:/usr/src/app
    depends_on:
      - mongo
      - storage_minio
      - redis

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./backend/api/db/mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  storage_minio:
    container_name: storage_minio
    image: minio/minio
    volumes:
      - ./services/minio:/storage
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /storage/uploads

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  notifications:
    build: ./backend/notifications
    ports:
      - '4000:4000'
    depends_on:
      - redis
