version: '3'

services:
  api:
    build: ./backend/api
    ports:
      - '3000:3000'
    volumes:
      - ./backend/api:/usr/src/app
    depends_on:
      - storage.minio
      - redis

  storage.minio:
    container_name: storage.minio
    image: minio/minio
    volumes:
      - ./backend/storage/uploads:/storage/uploads
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /storage

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  notifications:
    build: ./backend/notifications
    ports:
      - '4000:4000'
    depends_on:
      - redis
